### ISSUE TITLE
Kontakt podstranica u glavnom meniju ne radi

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#1]
Pojavljuje se greška Class 'inquiry' not found

FrontendController.php:1490

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Ovo nije riješeno

Ponoviti ću: 

Pojavljuje se greška Class 'inquiry' not found

FrontendController.php:1490

**Comment by dinobelegic** [comment]
done
