### ISSUE TITLE
Osmisliti testimonials

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#12]
"I could probably go into sales for you. I STRONGLY recommend Classified app to EVERYONE interested in running a successful online business! It's incredible."
- Nissa C.

Prevedi sa ove stranice još 2: 

https://termsfeed.com/reviews

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Super pregledna stranica. Odmah sam naletio na oglas koji trebam i riješio drva za ovu zimu!

Prepravi u : 

Super pregledna stranica. Brzo sam naišao na zanimljiv oglas i dogovorio drva za ovu zimu!

**Comment by dinobelegic** [comment]
done
