### ISSUE TITLE
Stranica za uređivanje oglasa se raspada

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#28]
http://prodaja-drva.com.hr/uredi-oglas/hvala-vam-sto-ste-odlucili-postati-registriranim-korisnikom-online-izdanja-vecernjeg-lista-e4da3
![image](https://cloud.githubusercontent.com/assets/9073175/17698386/41a13e78-63bb-11e6-94ed-11a3e838cb35.png)

Ova labela treba biti drugačija

![image](https://cloud.githubusercontent.com/assets/9073175/17698406/57496836-63bb-11e6-8941-00a9b42ffac5.png)

**Comment by dinobelegic** [comment]
done
