### ISSUE TITLE
Oglas je javno dostupan iako nije potvrđen

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#29]
http://prodaja-drva.com.hr/oglas/hvala-vam-sto-ste-odlucili-postati-registriranim-korisnikom-online-izdanja-vecernjeg-lista-e4da3

Objavio sam ga preko forme, otišao na svoj profil, pregledao listu oglasa, i mogao sam pristupiti tom oglasu, bez obzira što nije odobren u administraciji

**Comment by dinobelegic** [comment]
done
