### ISSUE TITLE
Ruta /sign-in ne postoji

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#4]
- poziva se nekoliko puta

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Kako je ovo riješeno? Naišao sam na nekoliko mjesta na webu, treba se okinuti funkcija za prijavu. Napravi da i ruta /prijava i /sign-in Okidaju istu funkciju

http://prodaja-drva.com.hr/sign-in

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Ne radi, i dalje je error da ruta ne postoji

http://prodaja-drva.com.hr/sign-in

**Comment by dinobelegic** [comment]
done
