### ISSUE TITLE
Title u rezultatima pretrage je neispravan

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#7]
Piše: Pretraga upita za  . $packaging

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Rezultati pretrage ne rade ako ne odaberem i Vrstu pakiranja i Vrstu drveta.

Kada ipak odaberem obadva i odabere se županija - onda je title 

```
<title>Rezultati pretrage upita briketi rinfuze 6 | Prodaja drva</title>
```

Ne valja. Bilo bi logičnije da piše: 

```
<title>Rezultati pretrage oglasa iz kategorija briketi i rinfuze u županiji + Ime županije | Prodaja drva</title>
```

**Comment by npapratovic** [comment]
Osim toga, treba nekako naznačiti da je to stranica rezuzltata pretrage, ovdje ne piše ništa. Ako nema niti jedan rezultat, onda to treba naznačiti

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Napiši ovako: 

"Rezultati pretrage: $vrsta-pakiranja, $vrsta-drveta, županija" 

http://prntscr.com/c6dsst

**Comment by dinobelegic** [comment]
done
