### ISSUE TITLE
Na stranici liste oglasa po kategoriji dodati ime kategorije u title i description

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/prodaja-drva#8]

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
Ne radi, otvorila mi se samo blank page

**Comment by dinobelegic** [comment]
done

**Comment by npapratovic** [comment]
![image](https://cloud.githubusercontent.com/assets/9073175/17698036/0274f0a2-63b9-11e6-92da-35a373c6a54d.png)

Treba pisati "županije" umjesto "zupanije"

**Comment by dinobelegic** [comment]
done
